/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/front/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Search */
        get: operations["front_front_api_api_front_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Autocomplete */
        get: operations["front_front_api_api_front_autocomplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/church/{church_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Church Details */
        get: operations["front_front_api_api_front_church_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/dioceses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Get Dioceses */
        get: operations["front_front_api_api_front_get_dioceses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AggregationOut */
        AggregationOut: {
            /**
             * Type
             * @enum {string}
             */
            type: "diocese" | "parish" | "municipality";
            /** Name */
            name: string;
            /** Church Count */
            church_count: number;
            /** Centroid Latitude */
            centroid_latitude: number;
            /** Centroid Longitude */
            centroid_longitude: number;
            /** Min Latitude */
            min_latitude: number;
            /** Max Latitude */
            max_latitude: number;
            /** Min Longitude */
            min_longitude: number;
            /** Max Longitude */
            max_longitude: number;
        };
        /** ChurchOut */
        ChurchOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Address */
            address: string | null;
            /** Zipcode */
            zipcode: string | null;
            /** City */
            city: string | null;
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** EventOut */
        EventOut: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** End */
            end: string | null;
            /** Schedules Indices */
            schedules_indices: number[];
            /** Source Has Been Moderated */
            source_has_been_moderated: boolean;
        };
        /** SearchResult */
        SearchResult: {
            /** Churches */
            churches: components["schemas"]["ChurchOut"][];
            /** Aggregations */
            aggregations: components["schemas"]["AggregationOut"][];
        };
        /** AutocompleteItem */
        AutocompleteItem: {
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Context */
            context: string | null;
            /** Url */
            url: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Uuid */
            uuid?: string | null;
        };
        /** ChurchDetails */
        ChurchDetails: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Address */
            address: string | null;
            /** Zipcode */
            zipcode: string | null;
            /** City */
            city: string | null;
            /** Events */
            events: components["schemas"]["EventOut"][];
            website: components["schemas"]["WebsiteOut"];
            /** Schedules */
            schedules: components["schemas"]["ScheduleOut"][];
            /** Parsings */
            parsings: components["schemas"]["ParsingOut"][];
        };
        /**
         * FeedbackTypeEnum
         * @enum {string}
         */
        FeedbackTypeEnum: "good" | "outdated" | "error" | "comment";
        /** ParsingOut */
        ParsingOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Scraping Url */
            scraping_url: string | null;
            /** Image Url */
            image_url: string | null;
        };
        /** ReportOut */
        ReportOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            feedback_type: components["schemas"]["FeedbackTypeEnum"];
            /** Comment */
            comment: string | null;
            /** Sub Reports */
            sub_reports: components["schemas"]["ReportOut"][];
        };
        /** ScheduleOut */
        ScheduleOut: {
            /** Explanation */
            explanation: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
        };
        /** SourceOut */
        SourceOut: {
            source_type: components["schemas"]["SourceTypeEnum"];
            /** Parsing Uuid */
            parsing_uuid: string | null;
        };
        /**
         * SourceTypeEnum
         * @enum {string}
         */
        SourceTypeEnum: "parsing" | "oclocher";
        /** WebsiteOut */
        WebsiteOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
            /** Home Url */
            home_url: string;
            /** Reports */
            reports: components["schemas"]["ReportOut"][];
        };
        /** ErrorSchema */
        ErrorSchema: {
            /** Detail */
            detail: string;
        };
        /** DioceseOut */
        DioceseOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Min Latitude */
            min_latitude: number;
            /** Max Latitude */
            max_latitude: number;
            /** Min Longitude */
            min_longitude: number;
            /** Max Longitude */
            max_longitude: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    front_front_api_api_front_search: {
        parameters: {
            query?: {
                latitude?: number | null;
                longitude?: number | null;
                min_lat?: number | null;
                min_lng?: number | null;
                max_lat?: number | null;
                max_lng?: number | null;
                date_filter?: string | null;
                hour_min?: number;
                hour_max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
        };
    };
    front_front_api_api_front_autocomplete: {
        parameters: {
            query: {
                query: string;
                latitude?: number | null;
                longitude?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutocompleteItem"][];
                };
            };
        };
    };
    front_front_api_api_front_church_details: {
        parameters: {
            query?: {
                date_filter?: string | null;
                hour_min?: number;
                hour_max?: number;
            };
            header?: never;
            path: {
                church_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChurchDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    front_front_api_api_front_get_dioceses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DioceseOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
}
